// Catálogo de cobertura comercial; no equivale al nomenclador postal oficial.
export const LOCALIDADES = [
  'Almirante Brown',
  'Avellaneda',
  'Berazategui',
  'Berisso',
  'CABA',
  'Campana',
  'Cañuelas',
  'Del Viso',
  'Derqui',
  'Esteban Echeverría',
  'Ezeiza',
  'Florencio Varela',
  'Hurlingham',
  'Ituzaingó',
  'José C. Paz',
  'La Matanza Norte',
  'La Matanza Sur',
  'Lanús',
  'Lomas de Zamora',
  'Malvinas Argentinas',
  'Merlo',
  'Moreno',
  'Morón',
  'Nordelta',
  'Quilmes',
  'San Fernando',
  'San Isidro',
  'San Martín',
  'San Miguel',
  'Tigre',
  'Tres de Febrero',
  'Vicente López',
  'Ensenada',
  'Escobar',
  'Garín',
  'General Rodríguez',
  'Guernica',
  'Ingeniero Maschwitz',
  'La Plata Centro',
  'La Plata Norte',
  'La Plata Oeste',
  'Luján',
  'Marcos Paz',
  'Pilar',
  'San Vicente',
  'Villa Rosa',
  'Zárate',
] as const;
